### ISSUE TITLE
Pre-existing order-dependent test failures in test_lifecycle.py

### ISSUE THREAD

**Issue by haowjy** [haowjy/meridian-channel#147]
## Context
Found during startup-audit final gate test verification.

## What
Several tests in `tests/unit/core/test_lifecycle.py` fail when run as part of the full test suite but pass in isolation (38/38 in 0.97s). The failure is:

```
AttributeError: 'SpawnStartEvent' object has no attribute 'origin'
```

This occurs in `reduce_events()` when processing events from a global/shared spawn store that was contaminated by other tests running earlier in the suite. The `origin` field was added to `SpawnFinalizeEvent` but earlier tests create events without it, and a type confusion in event reduction causes a `SpawnStartEvent` to be accessed as if it were a `SpawnFinalizeEvent`.

Affected tests:
- `test_start_creates_spawn_record`
- `test_mark_running_updates_spawn_status`
- `test_record_exited_stores_exit_code`
- `test_record_exited_emits_process_exited_telemetry_after_write`

## What should be done
- Fix test isolation: ensure each test_lifecycle test uses its own spawn store / tmp_path, not a shared global
- Or fix `reduce_events()` to handle missing `origin` field gracefully on older events

## Where found
- `tests/unit/core/test_lifecycle.py`
- `src/meridian/lib/state/spawn/events.py:177`

**Comment by haowjy** [comment]
Addressed by the architecture refactor on `wt/arch/p1a-seam`. Pending merge to main.
